### ISSUE TITLE
Plugin doesn't work with JDK 11

### ISSUE THREAD

**Issue by mutcianm** [romanowski/hoarder#67]
Hoarder plugin uses a deprecated class `DatatypeConverter` which has been removed from JDK 11

**Comment by mutcianm** [comment]
```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
[17:45:14]	at sbt.inc.hoarder.MappableFormat$ObjectStringifier$$anonfun$objToString$2.apply(MappableFormat.scala:279)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$ObjectStringifier$$anonfun$objToString$2.apply(MappableFormat.scala:279)
[17:45:14]	at sbt.inc.hoarder.FormatTimer$.aggregate(FormatCommons.scala:16)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$ObjectStringifier$.objToString(MappableFormat.scala:278)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$APIsF$$anonfun$12.apply(MappableFormat.scala:144)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$APIsF$$anonfun$12.apply(MappableFormat.scala:144)
[17:45:14]	at sbt.inc.hoarder.FormatCommons$$anonfun$writePairs$1.apply(FormatCommons.scala:101)
[17:45:14]	at sbt.inc.hoarder.FormatCommons$$anonfun$writePairs$1.apply(FormatCommons.scala:96)
[17:45:14]	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[17:45:14]	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[17:45:14]	at sbt.inc.hoarder.FormatCommons$class.writePairs(FormatCommons.scala:96)
[17:45:14]	at sbt.inc.hoarder.MappableFormat.writePairs(MappableFormat.scala:16)
[17:45:14]	at sbt.inc.hoarder.FormatCommons$class.writeMap(FormatCommons.scala:91)
[17:45:14]	at sbt.inc.hoarder.MappableFormat.writeMap(MappableFormat.scala:16)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$APIsF$.write(MappableFormat.scala:147)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$$anonfun$write$4.apply$mcV$sp(MappableFormat.scala:41)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$$anonfun$write$4.apply(MappableFormat.scala:41)
[17:45:14]	at sbt.inc.hoarder.MappableFormat$$anonfun$write$4.apply(MappableFormat.scala:41)
[17:45:14]	at sbt.inc.hoarder.FormatTimer$.aggregate(FormatCommons.scala:16)
[17:45:14]	at sbt.inc.hoarder.FormatTimer$.time(FormatCommons.scala:23)
[17:45:14]	at sbt.inc.hoarder.MappableFormat.write(MappableFormat.scala:40)
[17:45:14]	at org.romanowski.hoarder.core.ZincSpecific$AnalysisMapperOpts.storeAnalysis(ZincSpecific.scala:40)
[17:45:14]	at org.romanowski.hoarder.core.FileBasedCompilationCache$class.exportAnalysisContent(FileBasedCompilationCache.scala:60)
[17:45:14]	at org.romanowski.hoarder.core.HoarderCompilationCache.exportAnalysisContent(HoarderCompilationCache.scala:7)
[17:45:14]	at org.romanowski.hoarder.core.FileBasedCompilationCache$class.exportCache(FileBasedCompilationCache.scala:39)
[17:45:14]	at org.romanowski.hoarder.core.HoarderCompilationCache.exportCache(HoarderCompilationCache.scala:7)
[17:45:14]	at org.romanowski.hoarder.core.HoarderEngine.exportCacheTaskImpl(HoarderEngine.scala:30)
[17:45:14]	at org.romanowski.hoarder.core.HoarderEngineCommon$class.exportCacheTaskImpl(HoarderEngineCommon.scala:25)
[17:45:14]	at org.romanowski.hoarder.core.HoarderEngine.exportCacheTaskImpl(HoarderEngine.scala:25)
[17:45:14]	at org.romanowski.hoarder.actions.Stash$$anonfun$stashImpl$1$$anonfun$apply$11$$anonfun$apply$12$$anonfun$5.apply(Stash.scala:79)
[17:45:14]	at org.romanowski.hoarder.actions.Stash$$anonfun$stashImpl$1$$anonfun$apply$11$$anonfun$apply$12$$anonfun$5.apply(Stash.scala:79)
[17:45:14]	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[17:45:14]	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[17:45:14]	at scala.collection.immutable.List.foreach(List.scala:318)
[17:45:14]	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[17:45:14]	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[17:45:14]	at org.romanowski.hoarder.actions.Stash$$anonfun$stashImpl$1$$anonfun$apply$11$$anonfun$apply$12.apply(Stash.scala:79)
[17:45:14]	at org.romanowski.hoarder.actions.Stash$$anonfun$stashImpl$1$$anonfun$apply$11$$anonfun$apply$12.apply(Stash.scala:76)
[17:45:14]	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[17:45:14]	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[17:45:14]	at sbt.std.Transform$$anon$4.work(System.scala:63)
[17:45:14]	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[17:45:14]	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[17:45:14]	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[17:45:14]	at sbt.Execute.work(Execute.scala:237)
[17:45:14]	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[17:45:14]	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[17:45:14]	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[17:45:14]	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[17:45:14]	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:45:14]	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[17:45:14]	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:45:14]	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[17:45:14]	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[17:45:14]	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by mutcianm** [comment]
![](https://i.kym-cdn.com/entries/icons/facebook/000/003/617/OkayGuy.jpg)

**Comment by edrevo** [comment]
@mutcianm, I think the issue was assigned back to you to validate it is fixed. In case anyone else bumps into this issue and is hesitant to use this plugin due to this issue: I have verified it works OK with OpenJDK 11
